name: QueroWorkar
description: Encontre as melhores vagas de TI aqui.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  html: ^0.14.0+3
  flutter_html: ^0.11.1
  transparent_image: ^1.0.0
  loading: ^1.0.2
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  equatable: ^1.1.1
  meta: ^1.1.8
  hydrated_bloc: ^3.0.0
  share: ^0.6.3+6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-Bold.ttf

  assets:
    - assets/
